# 作業 

### 1. [簡答題] 請問下列程式碼，運算結果分別為何？

```
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
```


In [14]:
import numpy as np

In [15]:
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 

print(a + a)

[ 40  60  80 100]


In [16]:
print(a + b)

[21 32 43 54]


In [17]:
print(a + c)

[21 31 41 51]


In [18]:
print(a + d)

[21 31 41 51]


In [19]:
a = np.array( [20,30,40,50] )
e = np.array( [1,2] )

print(a + e)

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

### 2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？


In [20]:
# 記得先 Import 正確的套件

import numpy as np

In [21]:
A = np.ones(3)*1
B = np.ones(3)*2

print((A+B)*(-A/2))

[-1.5 -1.5 -1.5]


### 3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？


In [22]:
A = np.ones((1,6))
B = np.ones((6,1))

print(A * B) #內積
print(A @ B) #外積

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[6.]]
